### ISSUE TITLE
Is there a text_width bug or what is wrong on this code?

### ISSUE THREAD

**Issue by marcel12bell** [jashkenas/ruby-processing#77]
string = "dddddddddddddddd"
textlen = text_width(string)
text string, 100, 100
line 100+textlen, 89, 100+textlen, 102

string2 ="drawerrormmmmmmm"
textlen2 = text_width(string2)
text string2, 100, 120
line 100+textlen2, 109, 100+textlen2, 122

**Comment by monkstone** [comment]
Hi @marcel12bellif you are still interested @benfry reports that processing-3.0 is working OK https://github.com/processing/processing/issues/2175#issuecomment-130485239 to use that you will need to use [JRubyArt](https://rubygems.org/gems/jruby_art) instead of ruby-processing, which is staying on processing-2.2.1.
